export const SET_ACTIVE_SECTION = 'SET_ACTIVE_SECTION';
export const SET_QUESTION_ONE_ANSWER = 'SET_QUESTION_ONE_ANSWER';
export const SET_QUESTION_TWO_ANSWER = 'SET_QUESTION_TWO_ANSWER';
export const SET_QUESTION_THREE_ANSWER = 'SET_QUESTION_THREE_ANSWER';
export const SET_QUESTION_FOUR_ANSWER = 'SET_QUESTION_FOUR_ANSWER';
export const SET_QUESTION_FIVE_ANSWER = 'SET_QUESTION_FIVE_ANSWER';
export const SET_QUESTION_SIX_ANSWER = 'SET_QUESTION_SIX_ANSWER';
export const SET_QUESTION_SIX_PART_ONE_ANSWER = 'SET_QUESTION_SIX_PART_ONE_ANSWER';
export const SET_QUESTION_SIX_PART_TWO_ANSWER = 'SET_QUESTION_SIX_PART_TWO_ANSWER';
export const SET_QUESTION_SIX_PART_THREE_ANSWER = 'SET_QUESTION_SIX_PART_THREE_ANSWER';
export const SET_QUESTION_SIX_PART_FOUR_ANSWER = 'SET_QUESTION_SIX_PART_FOUR_ANSWER';
export const SET_QUESTION_SIX_PART_FIVE_ANSWER = 'SET_QUESTION_SIX_PART_FIVE_ANSWER';
export const SET_QUESTION_SEVEN_PART_ONE_ANSWER = 'SET_QUESTION_SEVEN_PART_ONE_ANSWER';
export const SET_QUESTION_SEVEN_PART_TWO_ANSWER = 'SET_QUESTION_SEVEN_PART_TWO_ANSWER';

export const SET_SINGLE_ANSWER = 'SET_SINGLE_ANSWER';
export const SET_MULTIPLE_ANSWER = 'SET_MULTIPLE_ANSWER';